# Equivalent to central_heat.yaml; include only one of these overlays.
binary_sensor:
  - id: !remove nilan_ek_circulation_pump #118
  - id: !remove nilan_ek_heater_relay_1 #119
  - id: !remove nilan_ek_heater_relay_2 #120
  - id: !remove nilan_ek_heater_relay_3 #121
  - id: !remove nilan_external_radiator_heat #122

sensor:
  - id: !remove nilan_ek_return_temperature #213
  - id: !remove nilan_ek_supply_temperature #214
  - id: !remove nilan_external_heating_setpoint # IR1800

number:
  - id: !remove nilan_external_heating_offset_from_room_temp_set # HR1800
