packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files:
      - components/nilan/cts602-light.yaml
      ### INPUT REGISTER FILES ###
      - components/nilan/input/4.yaml
      - components/nilan/input/5.yaml
      - components/nilan/input/102.yaml
      - components/nilan/input/104.yaml
      - components/nilan/input/106.yaml
      - components/nilan/input/107.yaml
      - components/nilan/input/108.yaml
      - components/nilan/input/109.yaml
      - components/nilan/input/110.yaml
      - components/nilan/input/201.yaml
      - components/nilan/input/210.yaml
      - components/nilan/input/211.yaml
      - components/nilan/input/212.yaml
      - components/nilan/input/213.yaml
      - components/nilan/input/214.yaml
      - components/nilan/input/215.yaml
      ### HOLDING REGISTER FILES ###
      - components/nilan/holding/106.yaml
      - components/nilan/holding/107.yaml
      - components/nilan/holding/108.yaml
      - components/nilan/holding/109.yaml
      - components/nilan/holding/110.yaml
      - components/nilan/holding/111.yaml
      - components/nilan/holding/112.yaml
      - components/nilan/holding/113.yaml
      - components/nilan/holding/114.yaml
      - components/nilan/holding/115.yaml
      - components/nilan/holding/116.yaml
      - components/nilan/holding/117.yaml
      - components/nilan/holding/118.yaml
      - components/nilan/holding/119.yaml
      - components/nilan/holding/120.yaml
      - components/nilan/holding/121.yaml
      - components/nilan/holding/123.yaml
      - components/nilan/holding/125.yaml
      - components/nilan/holding/1700.yaml
      - components/nilan/holding/1701.yaml
    refresh: 0s

binary_sensor:
  - platform: template
    id: nilan_condenser_state
    name: Condenser state

#According to documentation, the address for cts602 should be 50. But it seems to be 0 as it is with the cts602 light
#sensor:
#- id: !extend nilan_protocol_node_address
#  address: 50