packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: split_into_separate_files
    files: 
      - components/nilan/comfort.yaml
      ### INPUT REGISTER FILES ###
      - components/nilan/input/109.yaml
      - components/nilan/input/110.yaml
      - components/nilan/input/201.yaml
      - components/nilan/input/209.yaml
      - components/nilan/input/211.yaml
      - components/nilan/input/212.yaml
      - components/nilan/input/213.yaml
      - components/nilan/input/214.yaml
      ### HOLDING REGISTER FILES ###
      - components/nilan/holding/100.yaml
      - components/nilan/holding/101.yaml
      - components/nilan/holding/102.yaml
      - components/nilan/holding/103.yaml
      - components/nilan/holding/104.yaml
      - components/nilan/holding/105.yaml
      - components/nilan/holding/109.yaml
      - components/nilan/holding/110.yaml
    refresh: 0s

sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet (before heater) temperature"
    id: nilan_inlet_temp_t2
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 202
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Condenser temperature"
    id: nilan_condenser_temp_t5
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 205
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Evaporator temperature"
    id: nilan_evap_temp_t6
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 206
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "AUX temperature"
    id: nilan_aux_temp_t16
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 216
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Preheater temperature"
    id: nilan_preheat_temp_t17
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 217
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Pressure pibe temperature"
    id: nilan_prepibe_temp_t18
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 218
    filters:
      - multiply: 0.01
      
###########################
#### HOLDING REGISTERS ####
###########################

binary_sensor:
  - platform: template
    id: nilan_bypass_state
    name: Bypass state
    device_class: opening

#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hotgas defrost"
    id: nilan_hotgas_defrost
    register_type: read
    address: 111

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Defrost termostat"
    id: nilan_defrost_termostat
    register_type: read
    address: 112
