substitutions:
  branch_ref: main

packages:
  remote_package:
    url: https://github.com/Jopand/esphome_components
    ref: ${branch_ref}
    files:
      - components/nilan/all.yaml
      # Input registers
      - components/nilan/input/102.yaml
      - components/nilan/input/104.yaml
      - components/nilan/input/105.yaml
      - components/nilan/input/106.yaml
      - components/nilan/input/108.yaml
      - components/nilan/input/113.yaml
      - components/nilan/input/114.yaml
      - components/nilan/input/115.yaml
      - components/nilan/input/1100.yaml
      - components/nilan/input/1103.yaml
      - components/nilan/input/1104.yaml
      - components/nilan/input/1204.yaml
      # Holding registers
      - components/nilan/holding/1200.yaml
      - components/nilan/holding/1201.yaml
      - components/nilan/holding/1202.yaml
      - components/nilan/holding/1203.yaml
      - components/nilan/holding/1204.yaml
    refresh: 0s

binary_sensor:
  - platform: template
    name: "Air filter alarm"
    id: nilan_filter_alarm
    lambda: |-
      return (id(nilan_alarm_list_1_id).state == 19
        || id(nilan_alarm_list_2_id).state == 19
        || id(nilan_alarm_list_3_id).state == 19);

text_sensor:
  - platform: template
    name: "Air filter alarm status"
    lambda: |-
      if (id(nilan_filter_alarm).state) {
        return {"Skift filter"};
      } else {
        return {"Filter OK"};
      }
