sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Condenser temperature"
    id: nilan_condenser_temp_t5
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 205
    filters:
      - multiply: 0.01
