sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Evaporator temperature"
    id: nilan_evap_temp_t6
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 206
    filters:
      - multiply: 0.01
