sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "EK supply temperature"
    id: nilan_ek_supply_temperature
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 214
    filters:
      - multiply: 0.01