binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heater relay 2"
    id: nilan_air_heater_relay_2
    register_type: holding
    address: 107
