binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "EK circulation pump"
    id: nilan_ek_circulation_pump
    register_type: holding
    address: 118