binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "EK heater relay 3"
    id: nilan_ek_heater_relay_3
    register_type: holding
    address: 121